name: "Monthly Meeting: %s"
desc: Test template for testing tests
lists: default
cards:
  - name: Update Meetup
    desc: Adjust hoster and speaker information on meetup.com
    due: -4 weeks
  - name: Announce Meetup
    desc: Click the announce button
    due: -4 weeks
  - name: Prepare Slides
    desc: Click the announce button
    due: -2 days

